### ISSUE TITLE
Empty array in the mapper throws an unhandled error

### ISSUE THREAD

**Issue by apandura-tibco** [project-flogo/flogo-web#1066]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
When I am editing the configuration of a task's inputs / iterator or trigger map inputs / reply, If I provide an empty array `[]` an unhandled exception is thrown and does not consider further changes to the value

![image](https://user-images.githubusercontent.com/23206463/54904890-abf67f80-4f05-11e9-94fb-627e1441627d.png)

**Expected behavior**

No exception must be thrown or should be handled properly. I should be able to save the changes to the value

**Minimal reproduction of the problem with instructions**
1. Open the configuration window of a task / trigger-handler.
2. Select inputs tab of a task / input - reply mappings tabs of trigger
3. Clear the input field and type in empty array `[]` 
4. Notice that there is an unhandled javascript error thrown and any further changes to the value is not recorded when I save the configuration window

* **Flogo version:** 0.5.8

* **Browser:** [all]

**Comment by fcastill** [comment]
Fixed by #1347
