### ISSUE TITLE
Error when i start  yarn start server

### ISSUE THREAD

**Issue by Hanane95** [project-flogo/flogo-web#1094]
I have error  when  i start  cmd  yarn start server 
![array](https://user-images.githubusercontent.com/24614539/57309240-3b7f7880-70d7-11e9-9890-bdd7f8bae4b8.PNG)

**Comment by fcastill** [comment]
You're probably using an older version of Node. Please use Node v10.14 or newer.

**Comment by fcastill** [comment]
I'm closing this issue, please let us know if you're facing more issues.
