### ISSUE TITLE
Mapping goes away when navigating out and into a flow

### ISSUE THREAD

**Issue by cpramodroy** [project-flogo/flogo-web#1103]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
Mapping data of return activity is lost when navigating out and into a flow. Noticed this behavior only when using "foreach" and "mapping" constructs.  If the following data is used for mapping the data was **not** lost.
`
{
  "books": [
   {
    "author":"xxxx",
    "titile":"xxxx",
    "price": 33.33
    }
  ] 
}
`

**Expected behavior**

Mapping should not get lost and must be saved. 

**Minimal reproduction of the problem with instructions**

**STEPS TO REPRODUCE:**
1. Create a flow with one output parameter of type "object".
2. Add any trigger, should not matter.
3. Add return activity and map the output object with the following data: 
`{
  "books": {
    "mapping": {
      "@foreach($flow.store.books)": {
        "author": "=$loop.author",
        "title": "=$loop.title",
        "price": "=$loop.price"
      }
    }
  }
}`
It does not matter if `$flow.store.books` exists or not. Make sure it is saved.
4.  Navigate out/back to "List of flows" section.
5. Navigate back into the created flow.
6. The mapping of return activity is lost and it is now empty.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Flogo version:** v0.9.0-rc.2 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX ]

[MappingIssue.zip](https://github.com/project-flogo/flogo-web/files/3200044/MappingIssue.zip)

**Comment by cpramodroy** [comment]
More caching related issues. All activities go away when navigating to/from List of flows sections. Please see attached screen recording.
[CacheIssue.zip](https://github.com/project-flogo/flogo-web/files/3213627/CacheIssue.zip)

**Comment by fcastill** [comment]
The fact that the properties have dots in their names is causing conflicts with some of the libs we use in the backend, the flow is not properly saved that's why when navigating back the data is lost

@ppaidi was looking into it. @ppaidi would you please provide more details about your findings?

**Comment by cpramodroy** [comment]
@fcastill When you say properties, are you referring to `$flow.store.books` ?

**Comment by fcastill** [comment]
@cpramodroy yes, sorry, I should've clarified I'm talking about the property names or keys of the JSON object that represents the mapping, in your example it's `@foreach($flow.store.books)`. We didn't foresee this new mapping syntax would cause conflicts with our server implementation.
