### ISSUE TITLE
Export app missed alias while rest trigger + rest invoke in the app

### ISSUE THREAD

**Issue by lixingwang** [project-flogo/flogo-web#1109]
**I'm submitting a ...**  (check one with "x")
```
[ *] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

- Create an app and add rest trigger + rest invoke activity
- Export the app
- The rest trigger and rest invoke as same ref "#rest", one of them should be tagged an alias
```
  "imports": [
    "github.com/project-flogo/contrib/activity/rest",
    "github.com/project-flogo/contrib/trigger/rest",
    "github.com/project-flogo/flow"
  ],
```
**Expected behavior**

Rest trigger or rest invoke should add a alias
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Flogo version:** 0.X.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX ]

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by apandurangi** [comment]
@lixingwang that is expected as the flogo engine considers aliases for triggers and activities separately. 

Let us know if it is creating any issues in building the application or runtime.

**Comment by fcastill** [comment]
This is the expected behavior, the aliases are scoped within types of contributions and it is enforced by the core library. If there are any issues with this behavior they should be open in the [core library](https://github.com/project-flogo/core)

**Comment by lixingwang** [comment]
@apandurangi @fcastill  thanks a lot.  Yes, it is expected behavior.
