### ISSUE TITLE
Unable to change the type of input / output of a resource

### ISSUE THREAD

**Issue by apandurangi** [project-flogo/flogo-web#1246]
## Environment

How are you running Flogo Web?

- [X] Docker : `flogo/flogo-web:unstable`
- [ ] Other (Provide details of your environment)

## Describe the bug

I am unable to change the type of input / output while defining the input / output of a resource. Happening for both stream and flow resources. 

## To Reproduce

1. Go to the stream / flow designer page
2. Open the define params popover
3. Try to change the existing input / outputs or add a new one

## Expected behavior

I should be able to choose a different type of my input

## Screenshots

![image](https://user-images.githubusercontent.com/23206463/68265617-9851f080-0072-11ea-8bbe-d2d1ce615726.png)

**Comment by fcastill** [comment]
It looks like the issue causes because we removed jquery, we missed that we were using jquery's dropdown in these components
