### ISSUE TITLE
Style issues in the application

### ISSUE THREAD

**Issue by ppaidi** [project-flogo/flogo-web#1251]
## Environment

How are you running Flogo Web?

- [x] Docker (Specify the docker image that you're using and the command you used to start the container) **docker run -it -p 5303:3303 flogo/flogo-web:unstable eula-accept**
- [ ] Other (Provide details of your environment)

## Describe the bug
1) Hover on the resource card while the menu still open
![image (3)](https://user-images.githubusercontent.com/47237691/68960196-b26b9b80-07f5-11ea-85cd-95595c0af56c.png)

2) Text input label alignment issue
![image (4)](https://user-images.githubusercontent.com/47237691/68960512-4b021b80-07f6-11ea-9ee5-407c419ecc78.png)

3) Stacking issue in stream designer
<img width="538" alt="Screen Shot 2019-11-14 at 3 08 07 PM" src="https://user-images.githubusercontent.com/47237691/68960737-cebc0800-07f6-11ea-9710-6764a74520cb.png">

4) Select button should have white background
<img width="1054" alt="Screen Shot 2019-11-14 at 3 36 50 PM" src="https://user-images.githubusercontent.com/47237691/68961124-9b2dad80-07f7-11ea-946d-16807e117475.png">

5) Activity titles in their configuration are cropped (In safari browser only)
<img width="767" alt="Screen Shot 2019-11-14 at 3 42 14 PM" src="https://user-images.githubusercontent.com/47237691/68961173-c57f6b00-07f7-11ea-8bd6-3171e65a0747.png">

6) Activity placeholders style issue (In Edge browser only)
<img width="458" alt="activityPlaceholderIssue" src="https://user-images.githubusercontent.com/47237691/68961435-679f5300-07f8-11ea-828d-c83642ae6487.PNG">

**Comment by fcastill** [comment]
@ppaidi can we close this?

**Comment by ppaidi** [comment]
Point 6 will be tracked in #1265
