### ISSUE TITLE
Streams: trigger element visible after opening trigger configuration modal

### ISSUE THREAD

**Issue by fcastill** [project-flogo/flogo-web#1260]
## Environment

How are you running Flogo Web?

- [ ] Docker (Specify the docker image that you're using and the command you used to start the container)
- [x] Other (Provide details of your environment): local dev env

## Describe the bug

Trigger icon from the stream designer panel is still visible after opening trigger config modal.

It only happens for streams, flows are not affected.

It's probably a side effect of #1227.

## To Reproduce

1. Navigate to the stream designer screen
1. Add a trigger to the stream
1. Click on trigger to open the trigger configuration AND don't move your mouse
1. Observe the trigger icon is still present
1. Move your mouse out of the trigger, the trigger will dissapear

## Expected behavior

trigger icon from the designer should not be visible after opening the trigger config modal

## Screenshots

<img width="468" alt="trigger-error" src="https://user-images.githubusercontent.com/17577698/70584245-5f2b0580-1b75-11ea-8036-e373cfec6e4e.png">

**Comment by ppaidi** [comment]
This is fixed as part of the PR [`166ec05` (#1320)](https://github.com/project-flogo/flogo-web/pull/1320/commits/166ec0553f50b1cc3797f94fb9237d228961c325)
