### ISSUE TITLE
Support "streamURI" in stream actions

### ISSUE THREAD

**Issue by apandurangi** [project-flogo/flogo-web#1269]
## Is your feature request related to a problem? Please describe.

With the changes to stream code in [project-flogo/stream](https://github.com/project-flogo/stream/pull/39), engine side stream execution can expect "stream" instead of "pipeline"

## Describe the solution you'd like

1. We need to update "pipelineURI" to "streamURI"
2. We need to allow users importing actions which has both new and old way of linking a stream resource to an action.
3. Always export the streams using the `streamURI" link in action

**Comment by fcastill** [comment]
We also have to support the `stream:` type/prefix for resource ids
