### ISSUE TITLE
Enhance the startup time

### ISSUE THREAD

**Issue by apandurangi** [project-flogo/flogo-web#1274]
## Is your feature request related to a problem? Please describe.

It takes a lot of time to start my flogo-web environment. The local flogo project `flogo-web` is being built with `sync imports` option every time in start up

## Describe the solution you'd like

We do not need to build the local Flogo project on every startup as it is already built while creating and contribution installation.

**Comment by fcastill** [comment]
we can get rid of this once the core, flow, streams and rest of the repos are tagged
