### ISSUE TITLE
Latest log messages are missing when I pop out to a new tab

### ISSUE THREAD

**Issue by apandurangi** [project-flogo/flogo-web#1291]
## Environment

How are you running Flogo Web?

- [X] Docker (Specify the docker image that you're using and the command you used to start the container)
- [X] Other (Provide details of your environment): Local 

## Describe the bug

The logs when pop out to a new window does not show all the log messages. When I test run a flow, I can see the latest information again. 

The same is not an issue with the floating log window

## To Reproduce

1. Go to a sample flow which can be tested
2. Click on 'Run Flow'
3. Open the logs in floating mode
4. Notice the log messages and time stamps
5. Click the pop out icon to open the logs in new window
6. Notice that the latest logs are missing

## Screenshots

![image](https://user-images.githubusercontent.com/23206463/75242829-d411f100-57ee-11ea-8e96-46fdb9410ee7.png)

![image](https://user-images.githubusercontent.com/23206463/75242879-ee4bcf00-57ee-11ea-8cfb-8ea2cad4111b.png)

**Comment by ppaidi** [comment]
Fixed in the PR #1328
