### ISSUE TITLE
Error building AWS Lambda function

### ISSUE THREAD

**Issue by retgits** [project-flogo/flogo-web#1293]
## Environment

How are you running Flogo Web?

- [x] Docker (started with `docker run --rm -it -p 3303:3303 flogo/flogo-docker eula-accept`)
- [ ] Other (Provide details of your environment)

## Describe the bug

Clicking on `build -> flogo-aws-lambda -> Linux/amd64` results in an error in the logs and no executable being built.

```bash
info: [17:04:40.199] Exec command: flogo create -f /flogo-web/local/engines/exported-app-build.json app-build in /flogo-web/local/engines
info: [17:04:40.203] run command: flogo create -f /flogo-web/local/engines/exported-app-build.json app-build
engine:create: 8283.393ms
info: [17:04:48.483] undefined {"durationMs":8285}
info: [17:04:48.484] [log] Build flogo: "flogo build -o,-e,--shim,aws_lambda_trigger" compileOpts:
info: [17:04:48.486] run command: flogo build -o -e --shim aws_lambda_trigger
[log] build output: Using build.go to build shim......

error: [17:04:54.896] /flogo-web/local/engines/app-build/bin is empty {"stack":"Error: /flogo-web/local/engines/app-build/bin is empty\n    at Object.recursivelyFindFirstFile (/flogo-web/apps/server/main.js:1732:15)"}
```
My flow is a Lambda trigger and a log activity.

Running Flogo Web version `flogo/flogo-docker                        latest              fb9649528a83`

As an additional suggestion, clicking `build -> flogo-aws-lambda` gives you the ability to select multiple operating systems for AWS Lambda, but only Linux/amd64 should be allowed given that AWS Lambda uses either Amazon Linux or Amazon Linux 2.

**Comment by fcastill** [comment]
The lambda trigger is handled specially in the UI and it looks like we forgot to update the reference of the lambda trigger to the new one 😅  
https://github.com/project-flogo/flogo-web/blob/8efb2055bc3335031434aef9f5570d74a7c8dc2c/libs/core/src/lib/constants/contributions-ref-placeholder.ts#L3-L4

I wonder if it's okay to handle only the new reference and ignore the old one? @mellistibco

**Comment by mellistibco** [comment]
@fcastill we can replace the ref with the new one. No need to maintain a ref for the old repo anymore.

**Comment by apandurangi** [comment]
@mellistibco could you please confirm if `github.com/project-flogo/aws-contrib/trigger/lambda` is the new Lambda trigger ref?

**Comment by mellistibco** [comment]
@apandurangi yup, thats the one.
