### ISSUE TITLE
Allow "datetime" data type

### ISSUE THREAD

**Issue by fcastill** [project-flogo/flogo-web#1296]
## Is your feature request related to a problem? Please describe.

The "datetime" data type was added to the flogo core project: https://github.com/project-flogo/core/pull/186

Flogo Web should support it.

## Describe the solution you'd like

- [x] Importing/exporting apps that reference the datetime type should be supported
- [x] Contributions that reference the datetime type should be supported
- [x] User should be able to edit the datetime type as a string without any issues (mapper, debugger panel, etc.)
- [x] Install datetime functions by default: https://github.com/project-flogo/contrib/tree/master/function/datetime

**Comment by ppaidi** [comment]
fixed in PR #1308
