### ISSUE TITLE
Flows: debugger panel scrollbar misalignment

### ISSUE THREAD

**Issue by fcastill** [project-flogo/flogo-web#1321]
## Environment

How are you running Flogo Web?

- [x] Docker (Specify the docker image that you're using and the command you used to start the container)
- [ ] Other (Provide details of your environment)

## Describe the bug

In flow when I select an activity that has both input and outputs and I open the debugger panel the panel content doesn't extend all the way to the right edge of the screen and there's a gap to the left of the scrollbar.

## To Reproduce

1. Create a flow
2. Add an activity that has both inputs and outputs
3. Select the activity and open the debugger panel
4. Observer the vertical scrollbar of the debugger panel content

Include error logs if applicable.

## Expected behavior

The scrollbar should be properly positioned.

## Screenshots

![Screen Shot 2020-08-04 at 2 48 33 PM](https://user-images.githubusercontent.com/17577698/89348604-abc1d480-d661-11ea-9387-8683f403e840.png)

**Comment by ppaidi** [comment]
Fixed in the PR #1326
