### ISSUE TITLE
Canvas page - Missing required configuration for an activity or trigger is not displayed on page load

### ISSUE THREAD

**Issue by apandurangi** [project-flogo/flogo-web#424]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request
```

**Current behavior**
When I first land to the flow details page, It does not declare the 'Required Configuration' message on the tiles upfront unless I select the tile. For example the Recieve HTTP Trigger and Invoke REST Service activity in my following flow does not record values for the required fields:
![image](https://cloud.githubusercontent.com/assets/23206463/25978065/8463e45e-36dd-11e7-87ec-4f82b89c3cee.png)

I can only view the configuration required state of the tile when I click on the tile to view the details:
![image](https://cloud.githubusercontent.com/assets/23206463/25978096/d28b1a08-36dd-11e7-9707-a7126f352130.png)

**Expected behavior**
It would be good if we can maintain the warning status of a tile while storing it in the data base such that we can show the notification to user upfront to the user. We can also let user know about missing required configuration in the Application details page where we list all the flows created within the application.

**Minimal reproduction of the problem with instructions**
1. Select an application from the application landing page.
2. Select a flow from the list of flows in the application which has an activity or trigger missing required configuration.
3. You will notice that the configuration required message is not shown upfront, when page loads. 
4. Select the activity or trigger which is missing the required configuration. Now you can see the Configuration required message is added to the tile.

* **Flogo version:** 0.3.4

**Comment by fcastill** [comment]
The UI has changed a lot since this issue was first opened. I'm closing this issue in favor of other issues that deal with client side resource level validation.
