### ISSUE TITLE
Implement a Flow visualizer

### ISSUE THREAD

**Issue by mellistibco** [project-flogo/flogo-web#476]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

**Expected behavior**
A flow visualizer that is capable of simply displaying/visualizing the layout of a flow. This can benefits apps that have refs to other flows (where we cannot actually change the flow). This should also be implemented in a way that it can be extracted from WebUI and used in other contexts, for example, via the flogo.io app showcase or Mashling recipes that have refs to flows.

**What is the motivation / use case for changing the behavior?**
Enable visualization of flows via refs and would-be app users the ability to visualize the flow logic without changing it. For example via flogo.io or Mashling's recipes.

**Comment by fcastill** [comment]
The flow visualization (or flow diagram as we call it in the codebase) has been refactored into an isolated reusable module that can be easily extracted as a flow visualizer. In fact, the diagram module is re-used internally to render both the flow visualization and the stream visualization.
